#!/bin/bash
# Build Script.  Use bash to run this script, bash grouper-ota from source directory
# Find out where the source directory is
export DIRSRC="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )";
export DEVICE=grouper;
if [ -e $DIRSRC/$DEVICE ];
then
    echo "Starting $DEVICE ota package build";
    echo "";
    bash $DIRSRC/$DEVICE;
    echo "$DEVICE ota package build finished";
    echo "";
    export DEVICE=tilapia;
    if [ -e $DIRSRC/$DEVICE ];
    then
        echo "Starting $DEVICE ota package build in 1 minute";
        echo "";
        sleep 60;
        echo "Starting $DEVICE ota package build";
        echo "";
        bash $DIRSRC/$DEVICE;
        echo "$DEVICE ota package build finished";
        echo "";
        echo "All ota packages are finished";
    else
        echo "error, needed $DIRSRC/$DEVICE bash script not found!";
    fi;
else
    echo "error, needed $DIRSRC/$DEVICE bash script not found!";
fi;
